#! /bin/sh
set -e

TARGET=/usr/share/icons/default/index.theme
ICONDIR=/usr/share/icons

# breeze_cursors with 602 priority
update-alternatives --install $TARGET x-cursor-theme \
    $ICONDIR/lingmo-light/cursor.theme 602

#DEBHELPER#
