#! /bin/sh
set -e

ICONDIR=/usr/share/icons

case "$1" in
    remove|deconfigure|failed-upgrade)
       update-alternatives --remove x-cursor-theme \
           $ICONDIR/lingmo-light/cursor.theme
    ;;
esac

#DEBHELPER#
